### ISSUE TITLE
[Bug] Server doesnt start

### ISSUE THREAD

**Issue by edvinbasil** [gabrielcsapo/starbuck#4]
I was trying to test this locally. So I cloned the repo and stared the server. But it gave me an error/
```
fn = function () { throw arg; };
                           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /<path_to_dir>/lib/starbuck.js:235:37
```
turns out `npm.commands.view` isnt returning any data.
Any ideas on how to fix this?

I'm using 
- node v0.15.3
- npm v6.4.1

**Comment by edvinbasil** [comment]
I had to change

_line 232, /starbuck/lib/starbuck.js_
```
npm.commands.view([name, 'versions', 'time'], true, function (err, data) {
```
to
```
npm.commands.view([name, 'versions', 'time'], false, function (err, data) {
```
as given by [this thread](https://npm.community/t/cannot-use-npm-view-command-programmatically/5455)
to fix the initial startup error. But this causes unnecessary logging to the console.

**Comment by gabrielcsapo** [comment]
👋 Hello @edvinbasil looking into this now.

**Comment by gabrielcsapo** [comment]
bumped a few dependencies and fixed the issue by moving to pacote instead of npm.

**Comment by edvinbasil** [comment]
Thanks. Looks like its fixed now
